### ISSUE TITLE
How to fit bounds when clusters points change?

### ISSUE THREAD

**Issue by riccardocaranfil** [leighhalliday/use-supercluster#11]
As the title, there is a way to handle points change out of the current viewport?

Cause inspected the clusters variable, it is filled only when the cluster is visible in the map

I'm using google-map-react

Thank you, Riccardo

**Comment by leighhalliday** [comment]
Hey @riccardocaranfil ! Hmmm... I think the way supercluster works is that it only worries about the current "viewport"... but I don't think there is anything stopping you from expanding the bounds an extra 10% or something like that??

```tsx
const { clusters, supercluster } = useSupercluster({
  points: [],
  bounds: [
    -1.2411810957931664,
    52.61208435908725,
    -1.0083656811012531,
    52.64495957533833,
  ].map(val => val * 1.10),
  zoom: 12,
  options: { radius: 75, maxZoom: 20 },
});
```

Or, you could have 2 instances, one for the viewport, and another for the expanded area you wish to cluster.
