### ISSUE TITLE
Can't retrieve leaves from supercluster when  too many leaves are present

### ISSUE THREAD

**Issue by tonnoz** [leighhalliday/use-supercluster#12]
Hello, I am trying to use the method  `supercluster.getLeaves(clusterId) `to retrieve all of the leaves of a cluster for the case when there are too many points to visualize at the lowest level but it seem not to be working. The method works only for clusters that are able to split apart further but not with the ones that present a very dense points concentration (like shown here https://youtu.be/3HYvbP2pQRA?t=2117 ). Is this a confimed issue?

**Comment by leighhalliday** [comment]
@tonnoz hey there! Because you're dealing with supercluster itself, you'll have to open up an issue on their repo... this one is sort of just the glue between React and Supercluster. Here they are: https://github.com/mapbox/supercluster
