### ISSUE TITLE
is it possible to have the objects inside the parent cluster?

### ISSUE THREAD

**Issue by AnasAlamin** [leighhalliday/use-supercluster#18]
i've been wondering if there is a way i can get an array of objects of all the data points that lies under the parent  cluster ?

**Comment by leighhalliday** [comment]
@AnasAlamin yup! there is a function called `getLeaves` which comes from supercluster itself that'll give you all the points within a specific cluster. In this package we expose an instance of supercluster in the return values from the hook, so you can then call functions on supercluster itself. https://github.com/mapbox/supercluster#getleavesclusterid-limit--10-offset--0
