### ISSUE TITLE
Spreading markers with the same geolocation

### ISSUE THREAD

**Issue by RicardoBrito1938** [leighhalliday/use-supercluster#31]
Hello guys, me again, good morning

Would you have any suggestion on how i could  show different markers from same location? i am able to get the children of the cluster, but i would like do spread them very closely where i could click on them,

on leaflet i saw something like this 

![image](https://user-images.githubusercontent.com/51454097/125122058-3c533100-e0cb-11eb-9d27-0e37ebdc1a9b.png)

spidering would be great, but just showing different markers for the same locations would be awesome

**Comment by afizsavage** [comment]
Hello Guys,

I want to get the children i.e the actual points that make up the cluster. Is that possible with this package ?

**Comment by RicardoBrito1938** [comment]
Hello Afiz, this is how i get the children, through .getChildren()

see the example below

` const { clusters, supercluster } = useSupercluster({
    points,
    bounds,
    zoom: viewport.zoom || 3,
    options: { radius: 75, maxZoom: 20 },
  });

 const clusterChildren = supercluster?.getChildren(cluster_id);

`

**Comment by afizsavage** [comment]
Thanks Ricardo. I can now get the children of the clusters. 

I also just realized that clusters can have other clusters as children depending on the zoom level.

**Comment by leighhalliday** [comment]
Thanks @RicardoBrito1938 for helping out!
