### ISSUE TITLE
Reduce option example is incorrect

### ISSUE THREAD

**Issue by Veldrovive** [leighhalliday/use-supercluster#34]
The reduce function is for merging two clusters which each have their own separate count.

As it is now, the `acc.count` is counting the number of times a merge has occurred which is not the same as `point_count`.
To make the example correct, `acc.count += 1` should be `acc.count += props.count`.

**Comment by leighhalliday** [comment]
Thanks @Veldrovive would you mind submitting a PR with a fix?

**Comment by leighhalliday** [comment]
Closing issue... happy to accept a PR that offers a fix.
