### ISSUE TITLE
useSupercluster gives back empty array when re-rendering points that have the same lat/lng values

### ISSUE THREAD

**Issue by davidprae** [leighhalliday/use-supercluster#5]
I'm using useSupercluster like below

```
  const { clusters } = useSupercluster({
    points,
    bounds,
    zoom,
    options: {
      radius: 75,
      maximumZoom
    }
  });
```

I have functionality that happens onClick of a map pin. It adds a `selected: true` property to the selected point. useSupercluster returns an empty array as the value for `clusters` once this operation is complete. 

Notes:
1) Nothing else changes (bounds, zoom, options)
2) Altering the values for the other inputs (bounds, zoom) kicks useSupercluster into gear and it returns what is expected (changing by zooming or shifting map)
3) This is occurring on a set of points that have the same exact lat/long values.
4) This does not occur on a set of points that do not share lat/long values.
5) This happens when clicking on a single point (i.e. no actual "clusters")

Any help is appreciated!
Thanks!

**Comment by leighhalliday** [comment]
Thanks @davidprae I'll try to take a look.

**Comment by ffjanhoeck** [comment]
@leighhalliday any updates on this ? :)

**Comment by talyh** [comment]
This seems to be related to this condition `!dequal(pointsRef.current, points)`.
At least for our scenario, `dequal` is not performing as expected.

**Comment by leighhalliday** [comment]
@ffjanhoeck @talyh @davidprae can one of you folks create a minimal example that has the issue? that way I can recreate it and look for a fix.

**Comment by leighhalliday** [comment]
@talyh I have bumped dequal from v1 to v2... hopefully they have fixed things that are causing issues. Going to mark this as closed unless a minimal reproducible example is shared that I can clone and play around with. I haven't been able to reproduce this on my own... sorry! Thanks for pointing me in the direction of dequal.

**Comment by spencerpauly** [comment]
Same issue here. I'll update this and let you know if the issue persists. Sounds like the bug being in dequal is a reasonable assumption.

**Comment by Mrsevic** [comment]
Same issue here as well.
