### ISSUE TITLE
Maximum update depth issue caused by using options inline with `map` and `reduce`

### ISSUE THREAD

**Issue by frednomoon** [leighhalliday/use-supercluster#54]
Hey there, I was stuck on this for a while but eventually realised I needed to define `options` as an object outside of my Component (apologies if I missed this somewhere in the docs?).

I guess that the functions are getting reinstantiated somewhere inside the component and causing this infinite loop? Anyway its annoying because the Type safety is decent when used inline which led me to think it would be safe.. will try make a PR to fix :)

**Comment by leighhalliday** [comment]
Hey @frednomoon !! Happy to look at a PR. Going to close this issue in the meantime.
