### ISSUE TITLE
seems to be returning `any` from hook

### ISSUE THREAD

**Issue by quinn-kontango** [leighhalliday/use-supercluster#57]
![image](https://user-images.githubusercontent.com/127759380/234306745-bcce7648-1c39-4a57-bb3a-c2e92d2855cb.png)

I attempted to explicitly set the generic types of the hook, but it is still returning `any`. Is this something that can be fixed here, or is it an underlying problem with the `supercluster` library

**Comment by quinn-kontango** [comment]
![image](https://user-images.githubusercontent.com/127759380/234308111-7723436f-7e0c-46ac-a036-8d8020b36ce1.png)

Also there are no type assertions on the inputs.

**Comment by leighhalliday** [comment]
Closing due to lack of response in PR. Happy to re-open.
