### ISSUE TITLE
Add compatibility with Supercluster v8

### ISSUE THREAD

**Issue by RodrigoTomeES** [leighhalliday/use-supercluster#60]
Hi,

Supercluster v8 has drop support to CommonJS and this has broken this packages when is used with Supercluster v8. Is interesting add support to ESM because Supercluser v8 has a lot of performance improvements.

The error is:

```bash
Error: require() of ES Module /Users/rodrigotome/Sites/nestar-storefront/node_modules/supercluster/index.js from /Users/rodrigotome/Sites/nestar-storefront/node_modules/use-supercluster/dist/use-supercluster.cjs.development.js not supported.
Instead change the require of index.js in /Users/rodrigotome/Sites/nestar-storefront/node_modules/use-supercluster/dist/use-supercluster.cjs.development.js to a dynamic import() which is available in all CommonJS modules.
```

Release notes of Supercluster v8 -> https://github.com/mapbox/supercluster/releases/tag/v8.0.0.

Maybe the only fix that the packages need is to set that it is a module in the package.json

Thanks

**Comment by KevinKreps** [comment]
PR waiting an approval + merge. Don't know how actively @leighhalliday is maintaining this project.
https://github.com/leighhalliday/use-supercluster/pull/59

I have copied the code into my own hook in my project just for now in the hopes that it is a temporary solution until this goes through.

**Comment by RodrigoTomeES** [comment]
Great, I hope that @leighhalliday look the pr and merge it

**Comment by marcinincreo** [comment]
@leighhalliday any news on this?

**Comment by jfilipeferreira96** [comment]
@leighhalliday could you help us out?

**Comment by federicocappellotto97** [comment]
+1

**Comment by GuyFawkesII** [comment]
+1 couldnt get it to work on nextJS
- error ./node_modules/use-supercluster/dist/use-supercluster.cjs.development.js:8:0
Module not found: ESM packages (supercluster) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/use-supercluster/dist/index.js

**Comment by KevinKreps** [comment]
I have published my fork, you can find it here: [https://www.npmjs.com/package/use-supercluster-with-supercluster-v8?activeTab=readme](https://www.npmjs.com/package/use-supercluster-with-supercluster-v8?activeTab=readme)

**Comment by leighhalliday** [comment]
Sorry y'all... I haven't been paying close attention to this repo. I'll get this merged even if it's 6 months late.

**Comment by leighhalliday** [comment]
PR has been merged and a new release has been cut to NPM. Upgrade to v1.0.0 for this.
