### ISSUE TITLE
Missing index.js file inside dist directory

### ISSUE THREAD

**Issue by AntoniakKacper** [leighhalliday/use-supercluster#72]
After installing use-supercluster package, package.json indicates as main: dist/index.js ("main": "dist/index.js",), but there is no index.js file inside dist directory.
![image](https://github.com/leighhalliday/use-supercluster/assets/68241246/47eec01d-d4f4-4f39-b290-1bcf47efa66d)

And i am getting error when running vitest tests,
![image](https://github.com/leighhalliday/use-supercluster/assets/68241246/6026d86e-c669-4300-a69f-8359ae195206)

**Comment by frederik-oestergaard** [comment]
+1 Experiencing the exact same issue.
![image](https://github.com/leighhalliday/use-supercluster/assets/78544875/200379a7-6077-4f85-9c91-65df20ae121d)


```JSON
"use-supercluster": "1.1.0",
"vitest": "0.34.6",
"vite": "4.5.0",
```
